### ISSUE TITLE
Share SASOFTCO manuals and repositories

### ISSUE THREAD

**Issue by danilonunezgil** [danilonunezgil/BPM_PC_S#24]

**Comment by olvegam** [comment]
I am searching for how to create a repository with repositories to organize the Sasoftco Development in one folder at this organization. Currently, the Sasoftco Development has three repos: Two for the front end and one for the back end (Camunda deployment).  Meanwhile, I will create a repo with the Manuals and a doc with the links of the current repos on GitHub.
