### ISSUE TITLE
Improve the Readme file

### ISSUE THREAD

**Issue by aglehd** [danilonunezgil/BPM_PC_S#27]
In the section of description, put two way to executing the tool.
1. SOFIS_CSV: This version generates a CSV file with the obtained results. 
 2, SOFIS_DB: This version uses a PostgreSQL database to store the obtained results.

And after, descrive each one  saying that the CVS version is the most recommended version.
It must change the name API for  "Requirements for executing the program"
The Prerequisites section is the description for compiling and deploying the program in local way , but I don't understand the first item "code editor": the user can modify the program? what program?

**Comment by olvegam** [comment]
Issue completed but I could not follow the procedure to make the change in one branch and then make a pull request.
