### ISSUE TITLE
Adjust the README for better users understanding

### ISSUE THREAD

**Issue by olvegam** [danilonunezgil/BPM_PC_S#5]
Please review this [link](https://coding-boot-camp.github.io/full-stack/es/github/professional-readme-guide) on README good practices and apply it to our README.

**Comment by olvegam** [comment]
In [this](https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/) other good practices source you can find a "What to Include in your README" section useful too.

**Comment by jhonalexander019** [comment]
updated readme, awaiting possible corrections

**Comment by olvegam** [comment]
¡wow! Excellent! It turned out great! congrats! a lot!
